# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1988e9e9eb10919b15fef0f88a048caf907921217bcafaa7c7117ca57e5418ef53ddc1b5efab433e70f7ee227952565da3df786323e076163d9b50db350ef101

test:
  secret_key_base: c51374a4b25098182249640b9a1652c5139e7338b772c9138b2f06f0030a219cd7dc7a19c8a0f11767a60de4c8ed622b0208de369547d07ec8afd0c6132c2b13

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
